"""Constants for the Samcla integration."""

from __future__ import annotations

DOMAIN = "samcla"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_PIN = "pin"
CONF_DEVICE_PSN = "device_psn"
CONF_HUB_PSN = "hub_psn"
CONF_HUB_MAC_RF = "hub_mac_rf"
CONF_VALVE_COUNT = "valve_count"

DEFAULT_PORT = 9000
DEFAULT_NAME = "Samcla Smart Home"

# Protocol transport
SAMCLA_AP_HOST = "10.0.0.1"
SAMCLA_LOCAL_PORT = 9000
CLOUD_HOST = "138.201.247.169"
CLOUD_PORT = 9001
SOCKET_TIMEOUT = 60.0
AP_CONNECT_DELAY = 2.0
LOCAL_AP_PAYLOAD_PREFIX = "0000000000000000"

# Protocol lines
LINE_READY = "READY"
LINE_OK = "OK"
LINE_ERR = "ERR"
LINE_INVALID_PIN = "INVALIDPIN"

# Commands
CMD_IRRIGSEQ = "SSH100_IRRIGSEQ"
CMD_IRRIGSIM = "SSH100_IRRIGSIM"
CMD_STOPCYCLE = "SSH100_SBP_STOPCYCLE"
CMD_STATS = "SSH100_STATS"
CMD_SYS_VERSION = "SYS_VERSION"
CMD_PUTJOB = "PUTJOB"
CMD_PUSH_CHECKJOB = "PUSH_CHECKJOB"

# IO status byte flags
BIT_IO_NOPROG = 0x10
BIT_IO_NOPROG_SBV = 0x08
BIT_IO_LIMIT_EXCEED = 0x20
BIT_IO_EVEON = 0x40

# Simultaneous valve selection bitmask
BIT_MANUAL_EV1 = 1
BIT_MANUAL_EV2 = 2
BIT_MANUAL_EV3 = 4
BIT_MANUAL_EV4 = 8
BIT_MANUAL_EV5 = 16
BIT_MANUAL_EV6 = 32
BIT_MANUAL_EV7 = 64
BIT_MANUAL_EV8 = 128
BIT_MANUAL_EV9 = 256
BIT_MANUAL_EV10 = 512

VALID_VALVE_COUNTS = (1, 2, 4, 6, 10)
SIMULTANEOUS_PLACEHOLDER_SUFFIX = "0000;ffff;0000;ffff;0000;ffff"
